INSERT INTO USER (id, user_id, password, name, email, CREATED_DATE_TIME, MODIFIED_DATE_TIME) VALUES (1, 'javajigi', 'test', '자바지기', 'javajigi@slipp.net', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER (id, user_id, password, name, email, CREATED_DATE_TIME, MODIFIED_DATE_TIME) VALUES (2, 'sanjigi', 'test', '산지기', 'sanjigi@slipp.net', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE_TIME, MODIFIED_DATE_TIME) VALUES (1, '1번 게시물', '1번 게시물입니다', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE_TIME, MODIFIED_DATE_TIME) VALUES (2, '2번 게시물', '2번 게시물입니다', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
