INSERT INTO USER(ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'tree', '1234', '희윤', 'gmldbs1109@naver.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'javajigi', 'test', '자바지기', 'javajigi@slipp.net');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (3, 'sanjigi', 'test', '산지기', 'sanjigi@slipp.net');

INSERT INTO QUESTION (ID, CONTENTS, CREATE_TIME, TITLE, WRITER_ID, STATUS) VALUES (1, '내용1111', CURRENT_TIMESTAMP, '제목1111', 1, TRUE);
