INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE, MODIFIED_DATE) VALUES ('sally', '1234', '새리', 'sally@codesquad.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL, CREATED_DATE, MODIFIED_DATE) VALUES ('codesquad', '4321', '코쿼', 'code@codesquad.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE, DELETED, MODIFIED_DATE) VALUES (1, '1번 게시물', '1번 게시물입니다', CURRENT_TIMESTAMP, FALSE, CURRENT_TIMESTAMP);
INSERT INTO QUESTION (WRITER_ID, TITLE, CONTENTS, CREATED_DATE, DELETED, MODIFIED_DATE) VALUES (2, '2번 게시물', '2번 게시물입니다', CURRENT_TIMESTAMP, FALSE, CURRENT_TIMESTAMP);
INSERT INTO ANSWER (CONTENTS, DELETED, CREATED_DATE, QUESTION_ID, WRITER_ID, MODIFIED_DATE) VALUES ('HIHI', FALSE, CURRENT_TIMESTAMP, 2, 1, CURRENT_TIMESTAMP);
